name: Build
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag"
        required: true
        type: string
  push:
    tags:
      - v0.*
jobs:
  build-client:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["18.x"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
        working-directory: client
      - name: Run lint
        run: pnpm run lint
        working-directory: client
      - name: Build client
        run: pnpm run build
        working-directory: client
      - name: Archive webapp artifacts
        uses: actions/upload-artifact@v3
        with:
          name: webapp
          path: client/dist/index.html
          retention-days: 1
  build-server:
    runs-on: ubuntu-latest
    needs: build-client
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Download webapp artifact
        uses: actions/download-artifact@v3
        with:
          name: webapp
          path: server/src/main/resources/web
      - name: Run build
        run: ./gradlew build
        working-directory: server
      - name: Get version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
      - name: Get version
        run: echo "RELEASE_VERSION=${{ inputs.tag }}" >> $GITHUB_ENV
        if: ${{ inputs.tag != '' && inputs.tag != null }}
      - name: Rename artifact
        run: mv server/build/libs/hvm-1.0-SNAPSHOT-fat.jar hvm-${RELEASE_VERSION}.jar
      - name: Archive artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: hvm-${{env.RELEASE_VERSION}}.jar
